### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by A7abhilash** [A7abhilash/weather-app#1]
The UI should look modern and decent. Please don't use too much of colors.

**Comment by Wendlereis** [comment]
Hey  i would like to work on it! Could you assing it to me?

I suggest someting like this:

<img src="https://cdn.dribbble.com/users/573900/screenshots/3828597/simply-weather-detail.png"  width="600"/>

Also, i notice that your api is not responding anymore, I suggest to migrate to[ OpenWeatherMap](https://openweathermap.org/api)

**Comment by A7abhilash** [comment]
@Wendlereis  Go ahead and also to access the api, you need to get an unique api key from darksky api website.

**Comment by Wendlereis** [comment]
They are not longer accepting new signups, so I am unable to take my own api key.

That is why I suggested to migrate to another one, what do you think?

Check here https://darksky.net/dev

**Comment by A7abhilash** [comment]
@Wendlereis Oh i see... Then u can go ahead with any api which you feel is good
