### ISSUE TITLE
Change app theme based on the weather and local time

### ISSUE THREAD

**Issue by tharindulucky** [A7abhilash/weather-app#4]
If the it's sunny day, the app should match the theme. If it's rainy should look like a wet glass. And so on. 

@A7abhilash I wish to work on this issue if you like.

**Comment by A7abhilash** [comment]
@tharindulucky You are good to go

**Comment by tharindulucky** [comment]
@A7abhilash Thanks! I'll start developments. Could you please assign me for this.

**Comment by tharindulucky** [comment]
@A7abhilash I added a PR #7  that adds this feature. Please review it and let me know what you think. Thanks!
